apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio
  template:
    metadata:
      labels:
        app: apicurio
    spec:
      containers:
        - name: apicurio
          image: apicurio/apicurio-studio:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            # HTTP/UI settings
            - name: QUARKUS_HTTP_PORT
              value: "8080"
            - name: QUARKUS_HTTP_ROOT_PATH
              value: "/"
            - name: STUDIO_UI_CONTEXT
              value: "/"

            # ✅ Correct DB settings for Apicurio Studio
            - name: APICURIO_DB_TYPE
              value: "postgresql"
            - name: APICURIO_DB_HOST
              value: "apicurio-db"
            - name: APICURIO_DB_PORT
              value: "5432"
            - name: APICURIO_DB_NAME
              value: "apicurio"
            - name: APICURIO_DB_USER
              value: "apicurio"
            - name: APICURIO_DB_PASS
              value: "apicurio"
