apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: bitnami/nginx:latest
          ports:
            - containerPort: 8080  # Bitnami NGINX uses 8080 by default, not 80
          volumeMounts:
            - name: vhosts
              mountPath: /bitnami/nginx/conf/vhosts
      volumes:
        - name: vhosts
          emptyDir: {}

