apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio-registry
  template:
    metadata:
      labels:
        app: apicurio-registry
    spec:
      containers:
        - name: registry
          image: apicurio/apicurio-registry:3.0.9
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: REGISTRY_FEATURES_ARTIFACTS_DELETE
              value: "true"
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://apicurio-db.argocd.svc.cluster.local:5432/apicurio"
            - name: QUARKUS_DATASOURCE_USERNAME
              value: "apicurio"
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: "apicurio"
            - name: QUARKUS_DATASOURCE_DB_KIND
              value: "postgresql"
            - name: QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
              value: "update"
