apiVersion: v1
kind: Service
metadata:
  name: apicurio-registry
  namespace: argocd
spec:
  selector:
    app: apicurio-registry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
